### ISSUE TITLE
WARNING: Using outdated gnuplot, use v4.0 for best results

### ISSUE THREAD

**Issue by peterjc** [gmarcais/mummer#14]
After runs ``gnuplot --version``, ``mummerplot.pl`` will depending on the return value print:

```
WARNING: Using outdated gnuplot, use v4.0 for best results
```

https://github.com/gmarcais/mummer/blob/v4.0.0beta/scripts/mummerplot.pl#L1502

First, this is confusing as the message appears if using more recent versions of gnuplot.

Second, should it say v4.0 or later? Is gnuplot 5.0.x acceptable?

**Comment by gmarcais** [comment]
Thanks for the bug report.

This message will only show up if gnuplot version 3 or earlier is the default version. It will not show up for version 4 or 5. I modified the message to say v4 or later. Yes, gnuplot 5 is acceptable.
