### ISSUE TITLE
How to compile from github source?

### ISSUE THREAD

**Issue by tseemann** [gmarcais/mummer#4]
How do I use yaggo?  (it's installed via brew)

```
git clone https://github.com/gmarcais/mummer.git
cd mummer

./configure
File not found

autoconf
configure.ac:4: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:5: error: possibly undefined macro: AM_SILENT_RULES
configure.ac:8: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:11: error: possibly undefined macro: AS_IF
configure.ac:27: error: possibly undefined macro: AC_DEFINE
configure.ac:80: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:83: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:87: error: possibly undefined macro: AM_COND_IF
```

**Comment by gmarcais** [comment]
To compile from the github tree, you need to have `autoconf` and `automake` installed. Yaggo needs to be in your path (check `which yaggo`), but it is not the source of the error above. Then do:

```Shell
autoreconf -fi
./configure
make
```

**Comment by tseemann** [comment]
Whoops, i used `autoconf` not `autoreconf`, sorry. 
It builds now.
Can you add the above to your INSTALL.md ?

**Comment by gmarcais** [comment]
I made a new release with updated instructions.

**Comment by YoannAnselmetti** [comment]
Hi,
Thanks a lot for this issue it helps me a lot.
In the INSTALL.md, the command line `autoreconf -fi` is still not present then I was not able to install mummer without this information...
Moreover, I had to install the library `libtool`.
You should add these two informations in the INSTALL.md file for future users.

I run the command lines `autoreconf -fi` and `./configure` that work fine but when I run `make`, I get the following error:
  YAGGO    tests/generate_sequences_cmdline.hpp
tests/generate_sequences_cmdline.yaggo:17: In Option genome-size|G: Option genome-size|G: Invalid unsigned integer '10M'
Makefile:2791 : la recette pour la cible « tests/generate_sequences_cmdline.hpp » a échouée
make: *** [tests/generate_sequences_cmdline.hpp] Erreur 1

**Comment by YoannAnselmetti** [comment]
I solved the problem by manually replacing 10M by 10000000.

**Comment by stevendbrown** [comment]
Replacing `10M` with `10000000` worked for me as well. I am running Ubuntu Linux with yaggo version 1.5.4.
