### ISSUE TITLE
src/essaMEM/mummer.cpp:221:6: error: #elif with no expression

### ISSUE THREAD

**Issue by pooranis** [gmarcais/mummer#7]
Hi Guillaume!  Thanks for this multithreaded mummer!!

I get this error when compiling the pre-release version.  If I remove the offending case, it's fine.

;)

**Comment by aic123** [comment]
I got zhe same  error .who know how to solve ?

**Comment by aic123** [comment]
hi.pooranis.  Have you solved it ?
I got the same error when  "make" .

**Comment by kevlim83** [comment]
Me too. Please update if this is already solved.

**Comment by MichelMoser** [comment]
in file src/essaMEM/mummer.cpp, line 221:

replacing #elif with #else 
solved the problem for me. 

But i dont know about the exact consequences as i dont program in C.
As its only about version control, it should not affect program behaviour i guess =)

**Comment by kevlim83** [comment]
@MichelMoser Thanks! It seems to work.

**Comment by aic123** [comment]
Thanks,MichelMoser.
I had solved this error in the same way.
I think the "VERSION" may not influence  the scripts.

**Comment by gmarcais** [comment]
It is fixed in the `develop` branch. Thanks for the bug report.
