### ISSUE TITLE
nucmer cannot write output

### ISSUE THREAD

**Issue by lfaller** [gmarcais/mummer#8]
Hi all,

I am trying to align a set of de novo assembled contigs against a reference genome using nucmer. However, the program complains that it couldn't use certain files (see below).

If I understand correctly, these are files that nucmer produces? However, I double-checked that I have write permissions to the current directory.

Thanks for any suggestion!

```
REF=E_coli.fasta
QUERY=contigs.fasta

$> ~/MUMmer3.23/nucmer ${REF} ${QUERY}

ERROR: The following critical files could not be used
out.delta
out.mgaps
out.ntref
Check your paths and file permissions and try again

$> ls -lah
total 9.0M
drwxr-xr-x 2 nobody nogroup 4.0K Apr 25 11:05 .
drwxrwxrwx 5 nobody nogroup 4.0K Apr 25 10:49 ..
-rwxr-xr-x 1 nobody nogroup 4.4M Apr 25 11:05 contigs.fasta
-rwxr-xr-x 1 nobody nogroup 4.6M Apr 25 11:05 E_coli.fasta
-rw-r--r-- 1 nobody nogroup  256 Apr 25 11:05 nucmer.error

$> less nucmer.error
20170425|105351| 16015| ERROR: The following critical files could not be used
20170425|105351| 16015| out.delta
20170425|105351| 16015| out.mgaps
20170425|105351| 16015| out.ntref
20170425|105351| 16015| Check your paths and file permissions and try again

$> ~/MUMmer3.23/nucmer --version
nucmer
NUCmer (NUCleotide MUMmer) version 3.1
```

**Comment by gmarcais** [comment]
Hi,

I am not the maintainer of version 3.23 of MUMmer, which you seem to be using. Things have changed significantly between 3.23 and 4.0.

That said, it looks that the directory you are working in is owned by nobody:nogroup. I doubt that is you! You don't have permission to write to that directory and nucmer fails.
