### ISSUE TITLE
mummerplot throws exception

### ISSUE THREAD

**Issue by Rhinogradentia** [gmarcais/mummer#9]
Hi,

I am trying to align contigs from a de-novo assembly against a reference strain sequence. When running mummerplot with the delta file following error is thrown:

```
mummerplot -p all all.delta 
gnuplot 5.0 patchlevel 3
Reading delta file all.delta
Writing plot files all.fplot, all.rplot
Writing gnuplot script all.gp
Forking mouse listener
Rendering plot to screen
WARNING: Unable to query clipboard with xclip

set mouse clipboardformat "[%.0f, %.0f]"
          ^
"all.gp", line 52: wrong option

WARNING: Unable to run 'gnuplot -geometry 500x500+0+0 -title mummerplot all.gp', Function not implemented
```
By removing the the line 1154 ($P_FORMAT .= "\nset mouse clipboardformat \"$MFORMAT\"";) everything works. 
My gnuplot version is 5.0 patchlevel 3.
By Installing xclip (version 0.12) the error message is slightly changed:

```
mummerplot -p all all.delta 
gnuplot 5.0 patchlevel 3
Reading delta file all.delta
Writing plot files all.fplot, all.rplot
Writing gnuplot script all.gp
Forking mouse listener
Rendering plot to screen

set mouse clipboardformat "[%.0f, %.0f]"
          ^
"all.gp", line 52: wrong option

WARNING: Unable to run 'gnuplot -geometry 500x500+0+0 -title mummerplot all.gp', Function not implemented
```
What do I have to install/change to get rid of the remaining error message, without removing the above mentioned line?

Thank you in advance

Best Regards,
Nadine

**Comment by oschwengers** [comment]
Hello,
same problem here (gnuplot version is 5.0 patchlevel 3). As it seems to be the standard "pure linux" way to visualize promer/nucmer alignments it would be very nice and helpful to have this fixed.
Thanks a lot in advance!

**Comment by gmarcais** [comment]
It seems that this command/option does not exists at all in gnuplot 5. The gnuplot program now check for the version of gnuplot before emitting the command. Not sure if we are loosing functionality here.

**Comment by ViriatoII** [comment]
I don't understand why this is closed, what is the solution after all?

**Comment by suryasaha** [comment]
Please see solution aka hack above in the original question. You can comment out the offending line in mummerplot.

**Comment by scubalaina** [comment]
Which file do you remove that line 1154 from? Thanks!

**Comment by Rhinogradentia** [comment]
> Which file do you remove that line 1154 from? Thanks!

Sorry, but I don't remember since this was already 3 years ago, but I think it was mummerplot itself in which I edited the line, since it is just a Perl script. And now it seems to be line 1155  [see](https://github.com/mummer4/mummer/blob/277dac5222ca19a59b09657b523bf9d2f088d6a3/scripts/mummerplot.pl#L1155 )

**Comment by thkuo** [comment]
It seemed actually a problem about parsing the gnuplot output (that is, its version). My solution was replacing https://github.com/mummer4/mummer/blob/277dac5222ca19a59b09657b523bf9d2f088d6a3/scripts/mummerplot.pl#L1495 
with 
```
$OPT_gpstatus = `gnuplot --version`;                                                                                                                                                                           
$OPT_gpstatus =~ /gnuplot ([0-9\.]+)/;
$OPT_gpstatus= $1;
```
My mummerplot and perl versions were 3.5 and v5.26.2, respectively. The authors might want to integrate this in the next release (if they also think so).

**Comment by gonzalezibeas** [comment]
In my case commenting out the single line of the code mentioned by Rhinogradentia was not enough. I had to comment out the 3 lines of "$P_FORMAT" (lines 1153, 1154, 1155 of mummerplot file). In the last version of mummer the problem persists:

mummer, 4.0.0rc1
GnuPlot, gnuplot 5.2 patchlevel 8

**Comment by Li-Alvarez** [comment]
I had the same issue and was able to solve it with what @thkuo suggests.
Replace line 1495 with:
$OPT_gpstatus = `gnuplot --version`;                                                                                                                                                                           
$OPT_gpstatus =~ /gnuplot ([0-9\.]+)/;
$OPT_gpstatus= $1;
